spec:
  name: "vacunas-sincronizador-configuracion-pacientes"
  version: "0.0.0"
  image:
    pullPolicy: "IfNotPresent"
    name: "vacunas-sincronizador-configuracion-pacientes"
    tag: "0.0.0.1"
  replicaCount: 1
  autoscaling:
    enabled: false
  service:
    port: 9080
  container:
    port: 9080
  ingress:
    enabled: true
  trafficManagement:
    ruleSet:
      - name: "route-to-metrics"
        prefix: "/vacunas-sincronizador-configuracion-pacientes/metrics"
        urlRewrite: "/metrics"
      - name: "route-to-health"
        prefix: "/vacunas-sincronizador-configuracion-pacientes/health"
        urlRewrite: "/health"
      - name: "route-to-service"
        prefix: "/vacunas-sincronizador-configuracion-pacientes/api/v1"
        urlRewrite: "/api/v1"
  corsPolicy: ~
  authentication:
    enabled: false
  authorization:
    enabled: false
  environment:
    configMap: ~
